In [9]:
import numpy as np

In [10]:
def PCA(mat):
    mat1 = mat
    m, n = mat.shape
    
    mean_A = mat1.mean(axis=0)
    print('Mean values of columns \n',mean_A)
    
    A_tilde = mat1 - mat1.mean(axis=0)
    print('\n Centered Matrix A_tilde \n', A_tilde)
    
    cov_A_tilde = np.matmul(A_tilde.transpose(),A_tilde) / m
    print('\n covariance matrix of the centered data \n', cov_A_tilde)
    
    eigen, vectors = np.linalg.eigh(cov_A_tilde)
    eigen = np.around(eigen,3)
    vectors = np.around(vectors,3)
    print('\n eigenvalues of the covariance matrix \n', eigen)
    print('\n eigenvectors corresponding to the eigenvalues \n ', vectors)
    
    #eigenvector matrix and transform the centered dataset with the matrix
    d_matrix = np.matmul(A_tilde,vectors)
    
    print('\n eigenvector matrix and transform the centered dataset with the matrix \n', d_matrix)
    
    #Variance 
    
    var_vals = np.around(np.var(d_matrix,axis=0),3)
    #print(var_vals)
    var_fun = lambda t: np.around(t/np.sum(var_vals),3)
    Eff_arr = np.around(np.array([var_fun(xi) for xi in var_vals]),3)
    print('\n Variance of all dimensions \n', var_vals)
    print('\n information is retained after the dimensionality reduction \n', np.round((np.max(var_vals) / np.sum(var_vals))*100,3))

In [11]:
a = np.matrix([[3,5,3,4,5],[1,4,2,3,5]]).transpose()

In [12]:
b = np.matrix([[1,2,3],[2,3,4]]).transpose()

In [13]:
PCA(a)

Mean values of columns 
 [[4. 3.]]

 Centered Matrix A_tilde 
 [[-1. -2.]
 [ 1.  1.]
 [-1. -1.]
 [ 0.  0.]
 [ 1.  2.]]

 covariance matrix of the centered data 
 [[0.8 1.2]
 [1.2 2. ]]

 eigenvalues of the covariance matrix 
 [0.058 2.742]

 eigenvectors corresponding to the eigenvalues 
  [[-0.851  0.526]
 [ 0.526  0.851]]

 eigenvector matrix and transform the centered dataset with the matrix 
 [[-0.201 -2.228]
 [-0.325  1.377]
 [ 0.325 -1.377]
 [ 0.     0.   ]
 [ 0.201  2.228]]

 Variance of all dimensions 
 [[0.058 2.744]]

 information is retained after the dimensionality reduction 
 97.93


In [14]:
PCA(b)

Mean values of columns 
 [[2. 3.]]

 Centered Matrix A_tilde 
 [[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]

 covariance matrix of the centered data 
 [[0.66666667 0.66666667]
 [0.66666667 0.66666667]]

 eigenvalues of the covariance matrix 
 [0.    1.333]

 eigenvectors corresponding to the eigenvalues 
  [[-0.707  0.707]
 [ 0.707  0.707]]

 eigenvector matrix and transform the centered dataset with the matrix 
 [[ 0.    -1.414]
 [ 0.     0.   ]
 [ 0.     1.414]]

 Variance of all dimensions 
 [[0.    1.333]]

 information is retained after the dimensionality reduction 
 100.0
